# URL: localhost:5432, база: finance_manager (как мы указали в docker-compose)
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_manager
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate: update значит, что Spring сам создаст таблицы, если их нет
spring.jpa.hibernate.ddl-auto=update
# Показывать SQL-запросы в консоли (очень полезно для обучения)
spring.jpa.show-sql=true
# Диалект для правильного понимания команд PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect